#%RAML 1.0 Trait

responses:
  400:
    body:
      application/json:
        example:
          {
            "message" : "BAD REQUEST"
          }
  401:
    body:
      application/json:
        example:
          {
            "message" : "UNAUTHONTICATED"
          }